#1070: Upgrade to Helm v3
mojaloop/helm pull request #285
Opened 2020-03-05 13:13 UTC by oderayi

2020-03-17 13:11 UTC, bushjames commented
@elnyry what is the timeline for helm version upgrade? This is pretty significant to current users and I suspect they will want time to test it before it becomes a necessity.

2020-03-17 13:29 UTC, elnyry commented
@bushjames Currently we're working on making the changes for Helm v3 then, we'll try things out on the dev environments first, to understand compatibility issues with current Helm version (v2) (Example, deploy v3 charts using v2 on cluster setup using v2, though there are no server changes needed for helm v3, etc). 

The plan (Miguel, Steven were I discussed it this morning) is to have two separate repos moving forward, a new repo (incubation) for Helm v3 to identify its behavior and then publish it only after internal validations. However, the plan is to keep the current helm repo intact to support implementations and adopters still using Helm v2 though we may not actively make changes to it, just to support Users already using it (unless its critical security, etc. issues).

Once we have a consensus or a general agreement, we can then move over to Helm v3 and then deprecate the Helm v2 repo at that time.

2020-03-20 13:32 UTC, elnyry commented
@oderayi was able to deploy this in AWS dev environments a couple of times with default values and were able to deploy it on our dev2 environment (mojadev2) with the values for dev2.

Below are the results of the Golden path and the results are promising (no issues so far).

However, we'll probably not be merging this and instead move this to a new repo to maintain versions for both helm 2 (for partners,  community members who need it) and helm 3 

![image](https://user-images.githubusercontent.com/10507686/77167900-e2e18000-6adc-11ea-8f63-1ee12d8f8ad4.png)

2020-08-26 10:51 UTC, mdebarros requested changes
If this PR is still applicable, please pull the latest changes from the master branch and resolve merge conflicts.

Also, see my one suggested comment.

2020-08-26 10:51 UTC, mdebarros commented on README.md
> +`helm uninstall <release-name>`
Please use `helm del <release-name>` <-- this will match the deployment guide changes for helm v3.

2020-10-25 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mojaloop/helm?pullRequest=285) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mojaloop/helm?pullRequest=285) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: oderayi<br/>:x: Sam<br/><hr/>**Sam** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mojaloop/helm?pullRequest=285) it.</sub>

2020-11-18 14:53 UTC, mdebarros commented
This issue has been resolved, refer to https://github.com/mojaloop/helm/issues/219 for more information.

2020-11-18 14:53 UTC, closed without merging