Feature/1569 refactor testing toolkit helm chart
mojaloop/helm pull request #387
Opened 2020-10-02 09:36 UTC by georgi-logodazhki

2020-10-06 12:35 UTC, vijayg10 requested changes

2020-10-06 12:35 UTC, vijayg10 commented on ml-testing-toolkit/realm/realm.json
> +      "realmRoles": ["offline_access", "uma_auhtorization"],
And also we should parameterize the password for hub.

2020-10-14 12:18 UTC, vijayg10 commented on ml-testing-toolkit/chart-backend/templates/config.yaml
> +  {{- end }}
Are you sure, these lines are with correct indentation?

2020-10-14 12:18 UTC, vijayg10 commented on ml-testing-toolkit/chart-backend/templates/config.yaml
> +  {{- end }}
Are you sure, these lines are with correct indentation?

2020-10-14 12:23 UTC, vijayg10 commented on ml-testing-toolkit/chart-backend/templates/config.yaml
> +  {{- end }}
I think those are ok

2020-10-14 12:23 UTC, vijayg10 commented on ml-testing-toolkit/chart-backend/templates/config.yaml
> +  {{- end }}
I think those are ok

2020-10-14 12:24 UTC, vijayg10 approved these changes

2020-10-19 12:59 UTC, elnyry-sam-k approved these changes

2020-10-19 13:31 UTC, merged