feat(pisp): enable `FEATURE_ENABLE_EXTENDED_PARTY_ID_TYPE` for ALS charts
mojaloop/helm pull request #430
Opened 2021-03-09 00:52 UTC by lewisdaly

I think I did this right... please let me know if there's anything missing here.

2021-03-09 07:49 UTC, elnyry-sam-k commented
hi Lewis, thanks for the PR :-)

Some comments (would've made inline but some of these weren't present):

1. Please update chart versions to 12.1.0 (as this seems to be a new feature; if not 12.0.1; all these should've been at 12.0.0 at least with the helm v12.0.0 release)
2. Please update the tags in values files (ALS, mojaloop)
3. Appversion in mojaloop/chart.yaml..

2021-03-09 11:15 UTC, lewisdaly commented
Thanks @elnyry-sam-k 

>Please update chart versions to 12.1.0 (as this seems to be a new feature; if not 12.0.1; all these should've been at 12.0.0 at least with the helm v12.0.0 release)

You mean for each item in `./mojaloop/requirements.yaml`?

2021-03-09 11:24 UTC, elnyry-sam-k commented
> Thanks @elnyry-sam-k
> 
> You mean for each item in `./mojaloop/requirements.yaml`?

Requirements - sure; but also the ALS charts themselves first..

2021-03-09 12:22 UTC, kleyow commented
I can't comment on helm specfic stuff too much but the ALS config looks good.

2021-03-10 07:34 UTC, elnyry-sam-k commented on account-lookup-service/values.yaml
>      log_transport: file
Tag values in this file as well :-)

2021-03-10 08:25 UTC, mdebarros requested changes
Hey @lewisdaly

I think you went a bit overboard on changing the appVersions.

2021-03-10 08:25 UTC, mdebarros commented on quoting-service/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on simulator/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on transaction-requests-service/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop-simulator/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop-bulk/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on mojaloop-bulk/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/requirements.yaml
> -  version: 11.0.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/chart-frontend/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/chart-connection-manager-frontend/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/chart-connection-manager-backend/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/chart-backend/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-testing-toolkit-cli/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-api-adapter/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-api-adapter/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-api-adapter/chart-service/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-api-adapter/chart-handler-notification/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on ml-api-adapter/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on finance-portal/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on finance-portal-settlement-management/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on emailnotifier/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralsettlement/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralsettlement/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralsettlement/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralsettlement/chart-service/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralsettlement/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/requirements.yaml
> +  version: 12.1.0
No change here required.

2021-03-10 08:25 UTC, mdebarros commented on centralledger/chart-handler-transfer-prepare/Chart.yaml
> +version: 12.1.0
No change here required.

2021-03-10 11:14 UTC, lewisdaly commented on account-lookup-service/values.yaml
>      log_transport: file
How about that Kustomise, eh?

2021-03-10 12:04 UTC, lewisdaly commented on als-oracle-pathfinder/Chart.yaml
> +version: 12.1.0
oops missed this one.

2021-03-10 12:04 UTC, lewisdaly commented on account-lookup-service/requirements.yaml
> +  version: 12.1.0
oops missed this one.

2021-03-10 12:43 UTC, elnyry-sam-k approved these changes
Thanks Lewis!

2021-03-10 14:35 UTC, merged