feat: upgrade to ml-testing-toolkit:v11.12.0
mojaloop/helm pull request #433
Opened 2021-03-25 17:10 UTC by shashi165

feat: https://github.com/mojaloop/project/issues/2098

2021-03-25 17:12 UTC, vijayg10 approved these changes

2021-03-26 09:32 UTC, mdebarros requested changes
Minor change on bumping chart version.

You will also need to update the mojaloop/requirements.yml to reference the correct version.

2021-03-26 09:32 UTC, mdebarros commented on ml-testing-toolkit/Chart.yaml
>  version: 11.0.1
Bump pls.

No magic here :D

2021-03-26 09:35 UTC, shashi165 commented on ml-testing-toolkit/Chart.yaml
>  version: 11.0.1
> Bump pls.
> 
> No magic here :D

GOSH 🤣

2021-03-26 09:44 UTC, mdebarros approved these changes
+1

2021-03-26 09:55 UTC, merged