feat(release): #2123 default settlement
mojaloop/helm pull request #438
Opened 2021-05-25 08:29 UTC by vgenev

* Added config for renamed and separated central-settlement handlers
* Upgraded central-ledger and central-settlement to support default settlement functionality
* Added `"allow.auto.create.topics": true` to consumers configs
* Added  `"auto.create.topics.enable": true` to kafka broker config

2021-05-25 14:19 UTC, mdebarros requested changes
Several comments for you attention.

2021-05-25 14:19 UTC, mdebarros commented on mojaloop/values.yaml
> +    centralsettlement-handler-grosssettlement:
`interchangeFeeCalculation.js` should not be defined for this service.

2021-05-25 14:19 UTC, mdebarros commented on central/values.yaml
> +        interchangeFeeCalculation.js: |
Should this not be removed as its only applicable to the rules handler?

2021-05-25 14:19 UTC, mdebarros commented on central/values.yaml
> +        api: central-settlement-grosssettlement.local
Is this Ingress not for the `centralsettlement-handler-rules`?

2021-05-25 14:19 UTC, mdebarros commented on centralsettlement/values.yaml
> +      api: central-settlement-rules.local
This should be for the `centralsettlement-handler-grosssettlement`?

2021-05-25 14:19 UTC, mdebarros commented on centralsettlement/values.yaml
> +centralsettlement-handler-grosssettlement:
`interchangeFeeCalculation.js` should not be defined this for the service.

2021-05-25 14:19 UTC, mdebarros commented on centralsettlement/values.yaml
> +        serviceName: central-settlement-handler-grosssettlement
Rules handler?

2021-05-25 14:19 UTC, mdebarros commented on centralsettlement/values.yaml
> +      api: central-settlement-grosssettlement.local
Rules?

2021-05-25 14:19 UTC, mdebarros commented on mojaloop/values.yaml
> +          api: central-settlement-rules.local
grosssettlement?

2021-05-25 14:19 UTC, mdebarros commented on mojaloop/values.yaml
> +            serviceName: central-settlement-handler-grosssettlement
rules handler?

2021-05-25 14:19 UTC, mdebarros commented on mojaloop/values.yaml
> +          api: central-settlement-grosssettlement.local
Rules handler?

2021-05-26 09:09 UTC, vgenev commented on centralledger/chart-handler-transfer-prepare/configs/default.json
> -    "ENABLE_ON_US_TRANSFERS": {{ .Values.config.enable_on_us_transfers }},
looks like some merge error

2021-05-26 09:13 UTC, vgenev commented on centralsettlement/chart-service/configs/default.json
> +              "client.id": "cs-con-notification-event",
but that's the notification-event consumer?

2021-05-26 09:18 UTC, vgenev commented on centralsettlement/requirements.yaml
>  #- name: forensicloggingsidecar
yeah :(

2021-05-28 07:44 UTC, mdebarros approved these changes
+1

2021-05-28 07:45 UTC, merged