Feature/change version 1.1
mojaloop/helm pull request #459
Opened 2021-11-25 13:42 UTC by vijayg10

2021-11-25 14:56 UTC, elnyry-sam-k approved these changes

2021-11-25 14:56 UTC, mdebarros requested changes
Tests are not passing yet

2021-11-25 15:37 UTC, mdebarros approved these changes

2021-11-25 15:38 UTC, mdebarros requested changes
Actually, please can you updated the release notes to indicate that additional parameters have been added to the environment configs for the test-cases.

2021-12-14 10:38 UTC, mdebarros approved these changes
+1

2021-12-14 10:40 UTC, merged